//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aula0610.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetTurma
    {
        public int DetTurma_Id { get; set; }
        public Nullable<int> Turma_Id { get; set; }
        public Nullable<int> Aluno_Id { get; set; }
    
        public virtual Aluno Aluno { get; set; }
        public virtual Turma Turma { get; set; }
    }
}
